version: "3"
services:
  theatreservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}:${TAG_NAME}
    container_name: theatreservice
    restart: on-failure
    depends_on:
      - mongocustom
    ports:
      - 8082:8082
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongocustom:27017/DATABASE1
    networks:
      - theater-net
  mongocustom:
    image: mongo:4.4
    container_name:  mongocustom
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      #- $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    networks:
      - theater-net

networks:
  theater-net:
    driver: bridge